manipulator:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 5
  goal_joint_tolerance: 0.0002
  goal_position_tolerance: 0.03
  goal_orientation_tolerance: 0.01