# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from pointing_gesture/PointingArmJoints.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class PointingArmJoints(genpy.Message):
  _md5sum = "a9f24fef50af6a7736edb41c88452247"
  _type = "pointing_gesture/PointingArmJoints"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 body_id           
int32 tracking_status

geometry_msgs/Point32 joint_position_right_elbow
geometry_msgs/Point32 joint_position_right_wrist 




================================================================================
MSG: geometry_msgs/Point32
# This contains the position of a point in free space(with 32 bits of precision).
# It is recommeded to use Point wherever possible instead of Point32.  
# 
# This recommendation is to promote interoperability.  
#
# This message is designed to take up less space when sending
# lots of points at once, as in the case of a PointCloud.  

float32 x
float32 y
float32 z"""
  __slots__ = ['body_id','tracking_status','joint_position_right_elbow','joint_position_right_wrist']
  _slot_types = ['int32','int32','geometry_msgs/Point32','geometry_msgs/Point32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       body_id,tracking_status,joint_position_right_elbow,joint_position_right_wrist

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PointingArmJoints, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.body_id is None:
        self.body_id = 0
      if self.tracking_status is None:
        self.tracking_status = 0
      if self.joint_position_right_elbow is None:
        self.joint_position_right_elbow = geometry_msgs.msg.Point32()
      if self.joint_position_right_wrist is None:
        self.joint_position_right_wrist = geometry_msgs.msg.Point32()
    else:
      self.body_id = 0
      self.tracking_status = 0
      self.joint_position_right_elbow = geometry_msgs.msg.Point32()
      self.joint_position_right_wrist = geometry_msgs.msg.Point32()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2i6f().pack(_x.body_id, _x.tracking_status, _x.joint_position_right_elbow.x, _x.joint_position_right_elbow.y, _x.joint_position_right_elbow.z, _x.joint_position_right_wrist.x, _x.joint_position_right_wrist.y, _x.joint_position_right_wrist.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.joint_position_right_elbow is None:
        self.joint_position_right_elbow = geometry_msgs.msg.Point32()
      if self.joint_position_right_wrist is None:
        self.joint_position_right_wrist = geometry_msgs.msg.Point32()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.body_id, _x.tracking_status, _x.joint_position_right_elbow.x, _x.joint_position_right_elbow.y, _x.joint_position_right_elbow.z, _x.joint_position_right_wrist.x, _x.joint_position_right_wrist.y, _x.joint_position_right_wrist.z,) = _get_struct_2i6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2i6f().pack(_x.body_id, _x.tracking_status, _x.joint_position_right_elbow.x, _x.joint_position_right_elbow.y, _x.joint_position_right_elbow.z, _x.joint_position_right_wrist.x, _x.joint_position_right_wrist.y, _x.joint_position_right_wrist.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.joint_position_right_elbow is None:
        self.joint_position_right_elbow = geometry_msgs.msg.Point32()
      if self.joint_position_right_wrist is None:
        self.joint_position_right_wrist = geometry_msgs.msg.Point32()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.body_id, _x.tracking_status, _x.joint_position_right_elbow.x, _x.joint_position_right_elbow.y, _x.joint_position_right_elbow.z, _x.joint_position_right_wrist.x, _x.joint_position_right_wrist.y, _x.joint_position_right_wrist.z,) = _get_struct_2i6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2i6f = None
def _get_struct_2i6f():
    global _struct_2i6f
    if _struct_2i6f is None:
        _struct_2i6f = struct.Struct("<2i6f")
    return _struct_2i6f
